from .ai_prompts import (
    IELTS_EXAMINER_SYSTEM_PROMPT,
    READING_GENERATION_PROMPT,
    LISTENING_GENERATION_PROMPT,
    WRITING_PROMPT_GENERATION,
    SPEAKING_PROMPT_GENERATION,
    QUESTION_GENERATION_PROMPT,
)

__all__ = [
    "IELTS_EXAMINER_SYSTEM_PROMPT",
    "READING_GENERATION_PROMPT",
    "LISTENING_GENERATION_PROMPT",
    "WRITING_PROMPT_GENERATION",
    "SPEAKING_PROMPT_GENERATION",
    "QUESTION_GENERATION_PROMPT",
]
